### ISSUE TITLE
Create a greyscale image?

### ISSUE THREAD

**Issue by ducpt2** [brainhubeu/reactNativeOpencvTutorial#1]
Can you make a example to create a greyscale image? or leave me some suggestion (openCV function or link).

Many thanks, love your work. <3

**Comment by Meph1k** [comment]
Hello @ducpt2 :)

https://www.tutorialspoint.com/java_dip/grayscale_conversion_opencv.htm

Does the approach above not work?
You may simply take the code from the link and place it in these files: 
https://github.com/brainhubeu/react-native-opencv-tutorial/tree/master/android/app/src/main/java/com/reactlibrary

as for example `
@ReactMethod
    public void getGrescaledImage(String imageAsBase64, Callback errorCallback, Callback successCallback)` here https://github.com/brainhubeu/react-native-opencv-tutorial/blob/master/android/app/src/main/java/com/reactlibrary/RNOpenCvLibraryModule.java

and you could call it inside your JS files as
`import { NativeModules } from 'react-native'
...
NativeModules.OpenCV.getGrescaledImage(image, cb1, cb2)
`

**Comment by ducpt2** [comment]
@Meph1k Thank you.
