### ISSUE TITLE
Canny Algorithm

### ISSUE THREAD

**Issue by robertogssoft** [brainhubeu/reactNativeOpencvTutorial#11]
Can I use canny algorithm? I need remove background and I want to recognize the contours and then remove the background

**Comment by Meph1k** [comment]
You may write any code in Objective-C and Java. Please, check native files :)

**Comment by piotr-s-brainhub** [comment]
@robertogssoft 

Do you think we can close this issue or you need any more help?

**Comment by piotr-s-brainhub** [comment]
@robertogssoft 

As you don't reply, I close this issue.
