### ISSUE TITLE
unable to add opencv dependency 

### ISSUE THREAD

**Issue by LochanRn** [brainhubeu/reactNativeOpencvTutorial#13]
Hey i went through your blog and trying to wire up OpenCV with react-native, i am unable to successfully add dependency in my react-native application. Would be really helpful if you can help through with it :) 
Also I am newbie to react-native and android studio please excuse me if it is a really very silly doubt. !!

![Screenshot (3)](https://user-images.githubusercontent.com/25365962/68004727-a7aef380-fc98-11e9-9da8-c67d285bfdc6.png)

This is the screenshot of the image, where I am stuck.   

I was able to successfully import the package and change the required versions for
compileSdkVersion
buildToolsVersion
minSdkVersion
targetSdkVersion
in my module build.gradle file as suggested by you. When I reach the part for dependency addition it does not show up anything request you to please help me out.

I am using android-opencv SDK version 4.1.1

The git link for my react-native application : https://github.com/LochanRn/OpenCV-React-Native.git

Thanks in advance.

**Comment by Tex2wo** [comment]
@LochanRn You closed it but didn't say how you fixed it for others to know
