### ISSUE TITLE
Receiving NativeModules empty object

### ISSUE THREAD

**Issue by Gricardov** [brainhubeu/reactNativeOpencvTutorial#18]
Chamo, I have a problem :(

I followed for step-by-step guide and I still can't get NativeModules to work. It's an empty object. I'm using RN 0.61.

Please help.

**Comment by piotr-s-brainhub** [comment]
@Gricardov 

do you think it's related with https://github.com/facebook/react-native/issues/26813 ?

**Comment by Gricardov** [comment]
> @Gricardov
> 
> do you think it's related with [facebook/react-native#26813](https://github.com/facebook/react-native/issues/26813) ?

Chamo, I finally found the solution. It seems it's a bug RN has. If you try all the proposed solutions and nothing works, then the answer is to turn the debugger on. That's how I finally got the NativeModules object.

Thanks for your response :)

**Comment by piotr-s-brainhub** [comment]
@Gricardov 

so could we close this issue?

**Comment by Gricardov** [comment]
Yes, chamo
