### ISSUE TITLE
Gradle project Sync failed

### ISSUE THREAD

**Issue by rockcs1992** [brainhubeu/reactNativeOpencvTutorial#2]
Hi guys, thanks for making this tutorial. I ran through the tutorial, cloned it and tried to make it run locally. However When I finished all of the steps as the tutorial instructed, I got the following error in Android studio: 

`Error:(29, 0) Could not find method compile() for arguments [project ':openCVLibrary341'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

I'm new to react native and android development. Do you guys know how to fix this? Any ideas? Thanks!

BTW I'm using android studio 2.3.1 and buildtoolsversion is 26.0.1. If this helps

**Comment by Meph1k** [comment]
Hello @rockcs1992!

Have you seen https://brainhub.eu/blog/opencv-react-native-image-processing/ ?

**Comment by rockcs1992** [comment]
@Meph1k Yeah I read it through before getting the error. However I just found that it's not the problem of the package. It turns out that the react-native initiation template is still using gradle 2 but react-native-camera now requires gradle 3 to work correctly. So I updated and synced the gradle file and solved the problem. Thanks for your response anyway, and sorry for bothering ^~^

**Comment by Meph1k** [comment]
@rockcs1992 no problem :). We're open for feedback and ready to help :)
