### ISSUE TITLE
 err [TypeError: null is not an object (evaluating '_OpenCV.default.checkForBlurryImage')]

### ISSUE THREAD

**Issue by devkrkanhaiya** [brainhubeu/reactNativeOpencvTutorial#22]
getting error while click on capture icon ..in Android 
![Screenshot 2020-05-18 at 4 56 26 PM](https://user-images.githubusercontent.com/49586754/82208098-91147500-9928-11ea-838c-53bd6b633209.png)

**Comment by piotr-s-brainhub** [comment]
@devkrkanhaiya 

Thanks for reporting this issue.
Could you provide more details (reproduction steps, Android version)?

**Comment by aidenmurphy89** [comment]
was a solution ever posted? I am experiencing the same error message running on IOS and I don't know how to fix it.

**Comment by CryShana** [comment]
I am very new to XCode, so when I got this issue on iOS I had no idea what was the problem either. I quickly figured out I simply had to select the `RNOpenCvLibrary.mm` file and target the right projects - the app and tests. Check screenshot below:

![image](https://user-images.githubusercontent.com/951230/110805319-4120e900-8281-11eb-8871-4655540800bf.png)

Hope this helps somebody.
