### ISSUE TITLE
Add instructions to include OpenCV in existing projects ?

### ISSUE THREAD

**Issue by omatrot** [brainhubeu/reactNativeOpencvTutorial#3]
Would it be possible to include steps to build OpenCV in existing Xcode and Android Studio projects ?
I've already ran the `downloadAndInsertOpenCV.sh` script. it worked well.
I have an existing react native project where I would like to include OpenCV compilation.
Thanks in advance.

**Comment by Meph1k** [comment]
@omatrot You're right! I will update the docs of how to implement in in the existing project. I should do it tomorrow. I will update you about the status ;)

**Comment by Meph1k** [comment]
@omatrot https://brainhub.eu/blog/opencv-react-native-image-processing/

Doesn't the blog post explain everything?
If there's something unclear, let me know, please :)

**Comment by omatrot** [comment]
@Meph1k The blog post helps a lot. Thanks. I'm looking for a cross platform C++ OpenCV source code base to use the same cross platform C++ consuming code for both iOS and Android.

**Comment by SwagatRanjit84** [comment]
@Meph1k  how to include opencv in react native?

**Comment by Meph1k** [comment]
@SwagatRanjit84 
https://brainhub.eu/blog/opencv-react-native-image-processing/

Please, follow the blog post. It's for RN :)

**Comment by piotr-s-brainhub** [comment]
@omatrot @SwagatRanjit84 

Can we close this issue or you want any more help?

**Comment by omatrot** [comment]
Yes I'm ok with that.
