### ISSUE TITLE
Android BUILD FAILED: Issue with Gradle Version?

### ISSUE THREAD

**Issue by ghost** [brainhubeu/reactNativeOpencvTutorial#4]
I get the following errors when I follow the steps for android:

$ react-native run-android
Scanning folders for symlinks in /PATH/react-native-opencv-tutorial/node_modules (21ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/PATH/react-native-opencv-tutorial/node_modules/react-native-camera/android/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33.879 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by Meph1k** [comment]
@AntaresRahman Looks like a problem with `react-native-camera`. Try this solution from https://github.com/react-native-community/react-native-svg/issues/584

**Comment by ghost** [comment]
Yes, I think it was both react-native-camera and react-native-svg. I ended up upgrading everything and keeping the versions consistent across the modules. The react-native documentation confused me, as it said it needs Android SDK 6.0 (API level 23) Marshmallow in specific, but it didn't make sense to not upgrade above Marshmallow. Thanks for the direction!
