### ISSUE TITLE
How i can use it for realtime imageprocesing?

### ISSUE THREAD

**Issue by DariusKopka** [brainhubeu/reactNativeOpencvTutorial#6]
Can you give exmaple code for a realtime imageprocesing?

For example capture a image from camera draw a rect with opencv and show it in realtime.

**Comment by Meph1k** [comment]
As far as I know it's highly unoptimised to process data in real time for camera in RN although it's still possible. You should check out https://github.com/react-native-community/react-native-camera for more information and you could call our openCV methods once every `n` milliseconds.

**Comment by piotr-s-brainhub** [comment]
@DariusKopka 

Are you happy with our answer or there's anything more you'd like to know?

**Comment by piotr-s-brainhub** [comment]
I close this issue as it's answered and the reporter hasn't asked for any more help for a long time.

**Comment by Sam1141968878** [comment]
> 我已经解决了这个问题，因为它已经得到回答，而且记者很久以来都没有寻求更多帮助。

How did you solve it?

**Comment by piotr-s-brainhub** [comment]
@liguanhan 

please check https://github.com/react-native-community/react-native-camera
