### ISSUE TITLE
How is it bridging react native and opencv?

### ISSUE THREAD

**Issue by SwagatRanjit84** [brainhubeu/reactNativeOpencvTutorial#8]
There is no proper code documentation of bridging between react native and opencv. Are they using native modules If yes then where? How the bridging is done?

**Comment by Meph1k** [comment]
@SwagatRanjit84 
Here:
https://github.com/brainhubeu/react-native-opencv-tutorial/blob/master/android/app/src/main/java/com/reactlibrary/RNOpenCvLibraryModule.java#L33

and here:
https://github.com/brainhubeu/react-native-opencv-tutorial/blob/master/android/app/src/main/java/com/reactnativeopencvtutorial/MainApplication.java#L40

and here:
https://github.com/brainhubeu/react-native-opencv-tutorial/blob/master/src/NativeModules/OpenCV.js#L3

Same for iOS

**Comment by SwagatRanjit84** [comment]
@Meph1k yeah got it done :)
